server:
  # CORRECCIÓN: El puerto debe ser 8081, no 8881.
  port: 8081

# Configuración de Spring
spring:
  # --- Configuración de Base de Datos (DataSource) ---
  # Configuración para desarrollo local (Fase 0-7)
  # Conexión a localhost y puertos expuestos por Docker Compose
  datasource:
    url: jdbc:postgresql://localhost:5433/inventory_db
    username: inventory_admin
    password: inv_secret_pass
    driver-class-name: org.postgresql.Driver

  # --- Configuración de JPA (Hibernate) ---
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  # --- Configuración de Flyway ---
  flyway:
    enabled: true
    locations: classpath:db/migration

  application:
    security:
      jwt:
        # Clave secreta (DEBE SER IDÉNTICA a la de beautycare-api)
        secret-key: "404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970"