server:
  port: 8080

# Configuración de Spring
spring:
  # --- Configuración de Base de Datos (DataSource) ---
  datasource:
    url: jdbc:postgresql://localhost:5432/beautycare_db
    username: beauty_admin
    password: admin_secret_pass
    driver-class-name: org.postgresql.Driver

  # --- Configuración de JPA (Hibernate) ---
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  # --- Configuración de Flyway ---
  flyway:
    enabled: true
    locations: classpath:db/migration

# --- Configuración de Seguridad (Fase 2) ---
# (Este bloque probablemente faltaba o estaba mal indentado)
application:
  security:
    jwt:
      # Clave secreta (Debe ser larga y segura)
      secret-key: "404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970"

# --- Configuración de servicios externos (Fase 5) ---
services:
  inventory:
    # URL base del microservicio para WebClient
    url: "http://localhost:8081"