server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/beautycare_db
    username: beauty_admin
    password: admin_secret_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration


application:
  security:
    jwt:
      secret-key: "404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970"

services:
  inventory:
    url: "http://localhost:8081"

logging:
  level:
    com.beautycare.core: DEBUG
    org.springframework.security: DEBUG